[profile.default]
src = "replay/src"
test = "replay/test"
script = "replay/script"
out = "replay/out"
cache_path = "replay/cache"
solc_version = "0.8.24"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
eth = "${ETH_RPC_URL}"
bsc = "${BSC_RPC_URL}"
arb = "${ARB_RPC_URL}"
base = "${BASE_RPC_URL}"
op = "${OP_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
avax = "${AVAX_RPC_URL}"
fantom = "${FTM_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
polygon_amoy = "${POLYGON_AMOY_RPC_URL}"
